In [ ]:
100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100

1. Import the numpy package under the name np (★☆☆)
numpy as np
import numpy as np
2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.show_config())
1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda\\Library\\include']
None
3. Create a null vector of size 10 (★☆☆)
10
print(np.zeros(10))
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
4. How to find the memory size of any array (★☆☆)
array = np.zeros((10,10))
array = np.zeros((10,10))
print("%d bytes" % (array.size * array.itemsize))
800 bytes
5. How to get the documentation of the numpy add function from the command line? (★☆☆)
.add
 np.info(np.add)
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.
    This is a scalar if both `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])
6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
array = np.zeros((10))
print(array)
array[5]=1
print(array)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
7. Create a vector with values ranging from 10 to 49 (★☆☆)
array=np.arange(10,49)
array=np.arange(10,49)
array
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])
8. Reverse a vector (first element becomes last) (★☆☆)
2
array=np.arange(0,11)
print(array)
array2= array[::-1]
print(array2)
​
[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
array
array= np.arange(0,9).reshape(3,3)
array
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
array=np.array([1,2,0,0,4,0])
array
non_zero=np.nonzero(array)
print ("Non zero elements:", non_zero)
Non zero elements: (array([0, 1, 4], dtype=int64),)
Create a 3x3 identity matrix
#### 11. Create a 3x3 identity matrix (★☆☆)

array=np.identity(3)
print(array)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
12. Create a 3x3x3 array with random values (★☆☆)
array
array = np.random.randint(1,100, size=(3,3))
print(array)
[[42  5 99]
 [26 64 14]
 [46 55 64]]
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
print(f"Minimum value :{data_min}, Maximum Value: {data_max}")
data = np.random.random((10,10))
data_min =np.min(data)
data_max= np.max(data)
print(f"Minimum value :{data_min}, Maximum Value: {data_max}")
Minimum value :0.010535060413441988, Maximum Value: 0.966448537582416
14. Create a random vector of size 30 and find the mean value (★☆☆)
3
array = np.random.random(30)
print(array)
mean = array.mean()
round_m = round (mean,2)
​
print(f"Mean value: {round_m}")
[0.41787238 0.93538779 0.70976317 0.42233903 0.81276587 0.157369
 0.10260818 0.19368872 0.39005929 0.22709621 0.56409163 0.23791344
 0.52706694 0.23831328 0.83533668 0.51312974 0.92320535 0.45670846
 0.00256704 0.16490676 0.36548704 0.8275407  0.62113277 0.70798943
 0.79590042 0.64207835 0.53827503 0.72051581 0.04742229 0.96675654]
Mean value: 0.5
15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
array = np.ones((5,5))
array[1:-1, 1:-1]=0
array
array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])
16. How to add a border (filled with 0's) around an existing array? (★☆☆)
array = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
False
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
array
array = np.diag([1, 2, 3, 4, 5])
print(array)
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
array = np.ones((3,3))
array = np.zeros((8,8),dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)
array = np.ones((3,3))
array = np.zeros((8,8),dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))
(1, 5, 4)
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)
array = np.ones((3,3))
array = np.zeros((8,8),dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Normalize a 5x5 random matrix
#### 22. Normalize a 5x5 random matrix (★☆☆)
x= np.random.random((3,3))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)
Original Array:
[[0.7200228  0.55116121 0.59437609]
 [0.73955492 0.59691829 0.21372457]
 [0.62065413 0.65069031 0.6274204 ]]
After normalization:
[[0.96285471 0.6417215  0.72390556]
 [1.         0.7287402  0.        ]
 [0.77387994 0.83100135 0.78674772]]